# Generated by Django 2.2.26 on 2022-01-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220111_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='time_minute',
        ),
    ]
